import { Link } from 'react-router-dom'

export default function Footer() {
  return (
    <footer className="border-t border-shuffle-200 pt-6 pb-8">
      <div className="max-w-3xl mx-auto px-4 text-center text-xs text-shuffle-400 space-y-2">
        <p>
          Stories generated by AI. Powered by{' '}
          <a href="https://claude.ai" className="hover:text-shuffle-600" target="_blank" rel="noopener noreferrer">
            Claude
          </a>
          {' · '}
          <Link to="/about" className="hover:text-shuffle-600">
            How this site works
          </Link>
          {' · '}
          <Link to="/blogs" className="hover:text-shuffle-600">
            Blog
          </Link>
          {' · '}
          <a href="https://buymeacoffee.com/dairylea" className="hover:text-shuffle-600" target="_blank" rel="noopener noreferrer">
            Buy Me a Coffee
          </a>
        </p>
        <p>
          <a href="https://dannycranmer.github.io/devtoolbox/" className="hover:text-shuffle-600" target="_blank" rel="noopener noreferrer">
            Dev Tools
          </a>
          {' · '}
          <a href="https://dannycranmer.github.io/parchment/" className="hover:text-shuffle-600" target="_blank" rel="noopener noreferrer">
            PDF Tools
          </a>
          {' · '}
          <a href="https://dannycranmer.github.io/imagetoolkit/" className="hover:text-shuffle-600" target="_blank" rel="noopener noreferrer">
            Image Tools
          </a>
        </p>
      </div>
    </footer>
  )
}
