#!/usr/bin/env bash
set -euo pipefail

# Shuffle Agent Runner
# Runs Claude Code to generate daily stories, then commits and pushes.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$SCRIPT_DIR/logs"
TODAY=$(date -u +%Y-%m-%d)
LOG_FILE="$LOG_DIR/$TODAY.log"

mkdir -p "$LOG_DIR"

log() {
  echo "[$(date -u '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "Starting Shuffle agent run for $TODAY"

# Pull latest changes
cd "$REPO_DIR"
log "Pulling latest from main..."
git pull --rebase origin main >> "$LOG_FILE" 2>&1

# Check if today's stories already exist
if [ -f "public/content/stories/$TODAY.json" ]; then
  log "Stories for $TODAY already exist. Skipping."
  exit 0
fi

# Run Claude Code with the prompt
log "Running Claude Code to generate stories..."
claude --print \
  --allowedTools "Bash(read-only:*),Edit,Write,WebSearch,WebFetch" \
  --model sonnet \
  "$(cat "$SCRIPT_DIR/prompt.md")" \
  >> "$LOG_FILE" 2>&1

# Validate the output file exists
if [ ! -f "public/content/stories/$TODAY.json" ]; then
  log "ERROR: Claude did not generate stories file for $TODAY"
  exit 1
fi

# Validate JSON is parseable
if ! python3 -c "import json; json.load(open('public/content/stories/$TODAY.json'))" 2>/dev/null; then
  log "ERROR: Generated JSON is invalid"
  rm -f "public/content/stories/$TODAY.json"
  exit 1
fi

# Commit and push
log "Committing and pushing stories..."
git add public/content/
git commit -m "Add stories for $TODAY

Generated by Shuffle agent (automated daily run)" >> "$LOG_FILE" 2>&1

git push origin main >> "$LOG_FILE" 2>&1

log "Successfully published stories for $TODAY"
